config/routes.rb
StaticPages::Application.routes.draw do
  resources :admins
  resources :participants, only: [:new, :create, :edit, :destroy, :update]
  root :to => 'static_pages#home'
  get "static_pages/home", :as => :home
  get "static_pages/about", :as => :about
  match "who-we-are" => 'static_pages#who_we_are', :as => :who_we_are
  match "/login" => 'admins#login', :as => :login
  match "/do_login" => 'admins#do_login', :as => :do_login
  match "/logout" => 'admins#logout', :as => :logout

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :nick, :password
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :email, :name
  validates :email, :presence => true,
            :uniqueness => true,
            :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :name, :presence => true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # GET /admins
  # GET /admins.json
  before_filter :signed?, except: [:do_login, :login, :logout]
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
    @admin = Admin.find(params[:id])
    @participants = Participant.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/new
  # GET /admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(params[:admin])

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admins/1
  # PUT /admins/1.json
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(params[:admin])
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to admins_url }
      format.json { head :no_content }
    end
  end

  def do_login
    @admin = Admin.find_by_nick_and_password(params[:nick], params[:password])
    if @admin
      session[:signed]=@admin.id
      redirect_to @admin
    else
      render :login
    end
  end

  def logout
    session[:signed]=nil
    redirect_to root_path
  end

  protected

  def signed?
    redirect_to login_path unless session[:signed]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def new
    @participant = Participant.new
    @admin = Admin.find(session[:signed])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /Participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
    @admin = Admin.find(session[:signed])
  end

  # POST /Participants
  # POST /Participants.json
  def create
    @participant = Participant.new(params[:participant])
    @admin = Admin.find(session[:signed])
    respond_to do |format|
      if @participant.save
        format.html { redirect_to admin_path(session[:signed]), notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /Participants/1
  # PUT /Participants/1.json
  def update
    @participant = Participant.find(params[:id])
    @admin = Admin.find(session[:signed])
    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to admin_path(session[:signed]), notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Participants/1
  # DELETE /Participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy
    @admin = Admin.find(session[:signed])
    respond_to do |format|
      format.html { redirect_to @admin }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def who_we_are
    @participants = Participant.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_links(links={})
    links.merge! 'Home' => home_path, 'Who We Are' => who_we_are_path, 'About' => about_path
    links.map { |k,v| content_tag(:li, link_to(k, v))}.join.html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def link_to_gravatar(email, size=150)
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}?d=wavatar&s=#{size}"
  end
end

app/views/admins/_form.html.erb
<%= form_for @admin, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @admin.errors.any? %>
        <div id="error_explanation" class="alert alert-error">
          <h4><%= pluralize(@admin.errors.count, "error") %> prohibited this album from being saved:</h4>

          <ul>
            <% @admin.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="control-group">
      <%= f.label :nick, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :nick, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :password, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  admins_path, :class => 'btn' %>
    </div>
<% end %>

app/views/admins/edit.html.erb
<% content_for(:title) { 'Edit' } %>
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/index.html.erb
<% content_for(:title) { 'Admins' } %>
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nick) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to admin.id, admin_path(admin) %></td>
        <td><%= admin.nick %></td>
        <td><%= admin.password %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_path(admin), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_path(admin),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_path,
            :class => 'btn btn-primary' %>

app/views/admins/login.html.erb
<% content_for(:title) { 'Login' } %>
<%= form_tag controller: "admins", action: "do_login", :html => { :class => 'form-horizontal' } do %>
    <div class="control-group">
      <%= label_tag :nick, "Nick", :class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag :nick, "", :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag :password, "Password", :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password, "", :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= submit_tag "Login", :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/admins/new.html.erb
<% content_for(:title) { 'New' } %>
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/show.html.erb
<% content_for(:title) { 'Show' } %>
<%- model_class = Admin -%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nick) %>:</strong></dt>
  <dd><%= @admin.nick %></dd>
</dl>

<table class="table table-striped">
  <thead>
  <tr>
    <th> Gravatar</th>
    <th> Name</th>
    <th> Email</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <% @participants.each do |participant| %>
      <tr>
        <td><%= image_tag link_to_gravatar participant.email, 50 %></td>
        <td><%= participant.name %></td>
        <td><%= participant.email %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant), :class => 'btn btn-warning' %></td>
        <td><%= link_to 'Delete', participant, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %></td>
      </tr>
  <% end %>
</table>

<div class="form-actions">
  <%= link_to 'New participant', new_participant_path(@album), :class => 'btn' %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admins_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_path(@admin), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_path(@admin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title><%= "Ruby Gardens :: #{ content_for(:title) }" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%= root_path %>">Rails Garden</a>

      <div class="container nav-collapse">
        <ul class="nav">
          <%= menu_links %>
          <% if session[:signed] %>
              <li><%= link_to 'LogOut', logout_path %></li>
              <li><%= link_to 'Admin', admin_path(session[:signed]) %></li>
          <% else %>
              <li><%= link_to 'LogIn', login_path %></li>
          <% end %>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span9">
        <%= yield %>
      </div>
    </div>
    <!--/row-->
  </div>
  <!--/content-->

  <footer>
    <p>&copy; Altoros 2012</p>
  </footer>

</div>
<!-- /container -->

<%= javascript_include_tag "application" %>

</body>
</html>

app/views/participants/_form.html.erb
<%= form_for @participant, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @participant.errors.any? %>
        <div id="error_explanation" class="alert alert-error">
          <h4><%= pluralize(@participant.errors.count, "error") %> prohibited this album from being saved:</h4>

          <ul>
            <% @participant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                @admin, :class => 'btn' %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<%- model_class = Participant -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/participants/new.html.erb
<%- model_class = Participant -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/static_pages/about.html.erb
<% content_for(:title) { 'About' } %>
<h1>About Ruby Gardens</h1>

<h4>О нас</h4>

<p>RubyGardens является сетью центров обучения, которые предоставляют возможность опытным разработчикам, владеющим различными языками программирования, пройти интенсивную переподготовку и стать Ruby девелопером.
Уже к этому абзацу будущим рубистам должно было наскучить читать информацию с налетом официоза, посему продолжим в более привлекательной манере. Если завтра вы проснетесь и решите, что Ruby является вашим призванием на ближайшие 50 лет, то прежде всего стоит начать со знакомства с людьми, с которыми вы, к гадалке не ходи, столкнетесь в первую очередь.
</p>

app/views/static_pages/home.html.erb
<% content_for(:title) { 'Home' } %>
<h1>Welcome to Ruby Gardens Home</h1>

<h4>Do IT Ruby Way!</h4>
<p>
  Приглашаем на курсы по Ruby on Rails! Осенний призыв на курсы RubyGardens стартует уже в сентябре, а это значит,
  что у всех желающих снова появляется возможность ступить на Ruby Way. RubyGardens позволяет в сжатые сроки переучиться
  на Ruby on Rails с любого языка web-разработки, а также получить полноценное обучение тем, кто только начинает свою профессиональную деятельность.
</p>

<h4>На кого рассчитан курс?  </h4>
<p>
  Мы приглашаем разработчиков, интересующихся Ruby on Rails, готовых в ближайшее время работать с данной технологией. Увлеченность и самостоятельное «копание» приветствуется!
  Впервые для участия в проекте приглашаются студенты 4-5 курсов технических ВУЗов!
  Предпочтение отдается кандидатам уже имеющим опыт web-разработки, со знанием английского языка не ниже Intermediate.
</p>

<iframe width="560" height="315" frameborder="0" src="http://www.youtube.com/embed/B591S_C16V4?rel=0">
</iframe>

<h4>При чем здесь Altoros?</h4>

<p>RubyGardens – внутренний образовательный проект компании Altoros. Почему мы «растим» Ruby-разработчиков?

1. Потому что в Altoros работает одна из самых крупных в Беларуси команда Ruby-разработчиков. Средний опыт работы в сфере IT у сотрудников отдела – 6 лет. 85% разработчиков – это специалисты Senior и Lead уровня.

2. Потому что Altoros участвует в Ruby-проектах компаний с мировым именем (RightScale, Shoedazzle, Couchbase и другие), что дает возможность получения уникального опыта работы, профессионального и карьерного роста.

3. Потому что мы любим Ruby, поддерживаем сообщество Ruby-разработчиков Беларуси и делаем все для развития данной технологии в нашей стране.

Данный набор – уже третий в RubyGardens. Сегодня наши выпускники работают на крупных проектах ведущих технологических компаний и строят успешную карьеру. Именно так все и получилось у Вадима Голуба, прошедшего у нас курс обучения прошлой зимой.
</p>

app/views/static_pages/who_we_are.html.erb
<% content_for(:title) { 'Who We Are' } %>
<h1>Who We Are</h1>
<ul>
  <table class="table table-striped">
    <thead>
    <tr>
      <th> Gravatar</th>
      <th> Name</th>
      <th> Email</th>
    </tr>
    </thead>
    <% @participants.each do |participant| %>
        <tr>
          <td><%= image_tag link_to_gravatar participant.email, 150 %></td>
          <td><%= participant.name %></td>
          <td><%= mail_to participant.email %></td>
        </tr>
    <% end %>
  </table>
</ul>